[debug] > Exec(run 1, None, None)
[debug] Evaluating tasks: Compile / run
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[error] java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:50051
[error] 	at io.grpc.netty.NettyServer.start(NettyServer.java:328)
[error] 	at io.grpc.internal.ServerImpl.start(ServerImpl.java:183)
[error] 	at io.grpc.internal.ServerImpl.start(ServerImpl.java:92)
[error] 	at network.master.Master.network$master$Master$$start(Master.scala:42)
[error] 	at network.master.Master$.main(Master.scala:24)
[error] 	at network.master.Master.main(Master.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] 	at sbt.Run.invokeMain(Run.scala:143)
[error] 	at sbt.Run.execute$1(Run.scala:93)
[error] 	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
[error] 	at sbt.Run$.executeSuccess(Run.scala:186)
[error] 	at sbt.Run.runWithLoader(Run.scala:120)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1981)
[error] 	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1920)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.util.Try$.apply(Try.scala:213)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: java.net.BindException: Address already in use: bind
[error] 	at java.base/sun.nio.ch.Net.bind0(Native Method)
[error] 	at java.base/sun.nio.ch.Net.bind(Net.java:459)
[error] 	at java.base/sun.nio.ch.Net.bind(Net.java:448)
[error] 	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
[error] 	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
[error] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
[error] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
[error] 	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
[error] 	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
[error] 	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
[error] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[error] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[error] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
[error] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[error] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[error] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (Compile / run) java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:50051
[error] Total time: 21 s, completed 2022. 11. 24. 오후 4:05:10
[debug] > Exec(idea-shell, None, None)
[debug] > Exec(, None, None)
[debug] > Exec(idea-shell, None, None)
